### ISSUE TITLE
Routes edit page not working for mobile

### ISSUE THREAD

**Issue by EdwinHoksberg** [EDSM-NET/FrontEnd#292]
Hi, when I try to edit a route(in Galactic mapping -> routes) on mobile the delete entry, move entry and add entry buttons all fail to work. This is the javascript error in my console when I load that page:
```
jquery.tablednd.js:95 Uncaught TypeError: Cannot set property 'touchstart' of undefined
    at String.<anonymous> (jquery.tablednd.js:95)
    at Function.each (jquery-3.3.1.min.js:2)
    at jquery.tablednd.js:94
    at jquery.tablednd.js:681
(anonymous) @ jquery.tablednd.js:95
each @ jquery-3.3.1.min.js:2
(anonymous) @ jquery.tablednd.js:94
(anonymous) @ jquery.tablednd.js:681

jquery-3.3.1.min.js:2 jQuery.Deferred exception: $(...).tableDnD is not a function TypeError: $(...).tableDnD is not a function
    at HTMLDocument.<anonymous> (https://www.edsm.net/en/galactic-routes/edit/id/1834:807:26)
    at l (https://code.jquery.com/jquery-3.3.1.min.js:2:29375)
    at c (https://code.jquery.com/jquery-3.3.1.min.js:2:29677) undefined
w.Deferred.exceptionHook @ jquery-3.3.1.min.js:2
c @ jquery-3.3.1.min.js:2
setTimeout (async)
(anonymous) @ jquery-3.3.1.min.js:2
u @ jquery-3.3.1.min.js:2
fireWith @ jquery-3.3.1.min.js:2
fire @ jquery-3.3.1.min.js:2
u @ jquery-3.3.1.min.js:2
fireWith @ jquery-3.3.1.min.js:2
ready @ jquery-3.3.1.min.js:2
_ @ jquery-3.3.1.min.js:2

jquery-3.3.1.min.js:2 Uncaught TypeError: $(...).tableDnD is not a function
    at HTMLDocument.<anonymous> (1834:807)
    at l (jquery-3.3.1.min.js:2)
    at c (jquery-3.3.1.min.js:2)
```

Is the code public somewhere? I wouldn't mind writing a fix for it :)

**Comment by AnthorNet** [comment]
Should be fixed ;) Thanks for your report.

**Comment by EdwinHoksberg** [comment]
Does it take a while for the changes to propagate? Because I'm still getting the same error.

**Comment by AnthorNet** [comment]
It should be online, may be a cache on your browser?

**Comment by EdwinHoksberg** [comment]
Yea it seems like a caching problem, I started a new private tab and now it's working fine, thank you!

AnthorNet <notifications@github.com> schreef op 5 juni 2019 16:10:52 GMT+07:00:
