### ISSUE TITLE
EDSM not updating credit balance, nor rank/reputation

### ISSUE THREAD

**Issue by VixTiniri** [EDSM-NET/FrontEnd#391]
EDSM has not updated my credit balance, or ranks, in more than 2 weeks.
https://www.edsm.net/en/user/profile/id/72966/cmdr/Mira+Tigerheart
This information remains stubbornly out-of-date.
Compare with Inara: https://inara.cz/cmdr/156166/

I can only assume this is some sort of bug.  Only EDSM has this de-sync problem.
I am using ED Market Connector 4.1.4, EDDI v.3.7.0, and ED Scout v1.7.1

**Comment by psdevil** [comment]
I have a similar issue. However, it only started after 22-Jan-2021 and still persists.
Money - incorrect
Reputation - incorrect
Rank - correct
Badges - correct

I have tried uploading all relevant journals over the last couple of days in case there was a lag in uploading and the data appearing. On each occasion I only managed to get a clean upload after several attempts of each file which I assume was down to server load.

I am using EDDiscovery v11.9.3.0 as the only upload source (apart from reloads).

As with VixTiniri, Inara shows it correctly, but I find EDSM more useful for many aspects and pretty awesome too :-)

**Comment by AnthorNet** [comment]
Still monitoring an issue with some Internal Error, it should be resolved now.

**Comment by psdevil** [comment]
> Still monitoring an issue with some Internal Error, it should be resolved now.

Thank you for taking the time to look into my issue. Sadly not quite resolved. 

1. The account book now shows all the recent entries and matches up with the in game value. Thank you. 
2. Unfortunately the graph and the balance value on the dashboard page are incorrect.
3. Reputation is still incorrect.

**Comment by AnthorNet** [comment]
Those 2 points should be only updated after loading the game again
